import type { Metadata } from 'next'
import { DM_Serif_Display, Montserrat } from 'next/font/google'
import './globals.css'

const sans = Montserrat({
  variable: '--google-font-sans',
  subsets: ['latin'],
})

const serif = DM_Serif_Display({
  variable: '--google-font-serif',
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${sans.variable} ${serif.variable} min-h-screen w-screen overflow-x-hidden antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
